name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: hoverkraft-tech/compose-action@v2.0.2

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 21

      - uses: DeLaGuardo/setup-clojure@12.3
        with:
          cli: 1.12.0.1479
          bb: latest

      - name: Cache maven
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.m2/repository
            /home/runner/.gitlibs
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: DB, Hasura migration 실행
        run: |
          clojure -X:dev:test
